"""sync models and db

Revision ID: 88bd0466d6f4
Revises: 
Create Date: 2025-11-06 18:02:41.352643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88bd0466d6f4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('intake_history', 'taken_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    op.add_column('users', sa.Column('last_synced_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_synced_time')

    op.alter_column('intake_history', 'taken_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
