version: "3.9"

services:
  db:
    image: postgres:15
    container_name: patients_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: patients_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  patients_service:
    build: .
    container_name: patients_service
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:password@db:5432/patients_db
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  db_data:
