"""Убрана user.role

Revision ID: 431e5474cc1d
Revises: 703edafcc08b
Create Date: 2025-10-19 16:07:34.895772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '431e5474cc1d'
down_revision: Union[str, Sequence[str], None] = '703edafcc08b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
